name: Deploy ToDoApp to AWS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible sshpass

      - name: Create private key file
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > aws_app_todo.pem
          chmod 600 aws_app_todo.pem

      - name: DÃ©ployment with Ansible
        run: |
          ansible-playbook -i /ansible/inventory_aws.ini /ansible/deploy.yml

      - name: Remove key file
        run: rm -f aws_app_todo.pem
